# Generated by Django 4.2.2 on 2023-06-14 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="My_User",
        ),
    ]
