# Generated by Django 4.2.2 on 2023-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0002_rename_user_my_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=64)),
                ("last_name", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("user_age", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="My_User",
        ),
    ]
